id: find_component
learningObjectives: 
- tbd
hints:
- tbd
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: OMG,${user.firstName}, did you see this?
        delay: 2000
      - text: <Add Image<
        delay: 3500
        - text: People are butchering our website on social media!
        delay: 2000
        - text: They’re saying it’s working sooooo slow. Some are comparing us to the last season of Game of Thrones! Sales are plumbing and our review ranking is going down. 
        delay: 3500
        - text: https://res.cloudinary.com/wilco/image/upload/v1666796470/wilco-assets/hackathon/26-10-2022se9jl_gsimage_lecxnz.png
        delay: 2000
        - text: This is serious. Creepy Joe from Sales is really pissed.
        delay: 2000
        - text: https://res.cloudinary.com/wilco/image/upload/v1666796470/wilco-assets/hackathon/Screen_Shot_2022-10-26_at_17.52.01_zqsqin.png
        delay: 2000
         - text: The worst thing that has happened to me since U2 launched that album with Apple straight into my iTunes”  he said!
We need to solve it ASAP.
        delay: 2000
        - text: Let’s fix it together, we’ll be done in no time.
        delay: 2000
        - text: Here’s the link to the page sales mentioned; please review the page and tell me which component is problematic. It’s probably rendering an unusual amount of times. 
        delay: 2000
        
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - mobile
          - - non web
          - - android
            - ios
          - - android
            - iphone
          - - android
            - mobile
          - - iphone
            - mobile
          - - ios
            - mobile
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Great! Seems like you found it. We;re a great team!
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Mmmmmm, I’m taking a look at it right now. I don’t think that’s the one, can you check again please?
              delay: 2500
