id: find_component
learningObjectives: 
- When a react component is being rendered
hints:
- Try and install the [React DevTools](https://github.com/facebook/react/tree/main/packages/react-devtools) extension on your browser, and see when components are being rendered.
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: OMG,${user.firstName}, did you see this?
        delay: 3500
      - text: People are butchering our website on social media!
        delay: 3500
      - text: They’re saying it’s working sooooo slow. Some are comparing us to the last season of Game of Thrones! Sales are plumbing and our review ranking is going down. 
        delay: 3500
      - text: https://res.cloudinary.com/wilco/image/upload/v1666796470/wilco-assets/hackathon/26-10-2022se9jl_gsimage_lecxnz.png
        delay: 3500
      - text: This is serious. Creepy Joe from Sales is really pissed.
        delay: 3500
      - text: https://res.cloudinary.com/wilco/image/upload/v1666796470/wilco-assets/hackathon/Screen_Shot_2022-10-26_at_17.52.01_zqsqin.png
        delay: 3500
      - text: We need to solve it ASAP.
        delay: 3500
      - text: Let’s fix it together, we’ll be done in no time.
        delay: 3500
      - text: Please review the Marketplace homepage and tell me which component is problematic. It’s probably rendering an unusual amount of times. 
        delay: 3500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - ItemList
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Great! Seems like you found it. We're a great team!
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: Mmmmmm, I’m taking a look at it right now. I don’t think that’s the one, can you check again please?
              delay: 2500
