id: number_of_renders
learningObjectives: 
- tbd
hints:
- tbd
startFlow:
  do:
  - actionId: bot_message
    params:
      person: keen
      messages:
      - text: Ok, it seems to have a problem, how many times does it render? 
        delay: 2000
      - text: "text2"
        delay: 3500
trigger:
  type: user_message
  params: 
    person: keen
  flowNode:
    if:
      conditions:
      - conditionId: text_contains_strings
        params:
          text: "${userMessageText}"
          strings:
          - - mobile
          - - non web
          - - android
            - ios
          - - android
            - iphone
          - - android
            - mobile
          - - iphone
            - mobile
          - - ios
            - mobile
      then:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: It definitely seems like it renders too many times. I mean, we don’t really need to render every time a visitor does <when project>. 
              delay: 1300
        - actionId: finish_step
      else:
        do:
        - actionId: bot_message
          params:
            person: keen
            messages:
            - text: I’m not seeing the same thing on my end, can you please recheck?
              delay: 2500
